[project]
name = "tipJarDapp"
authors = []
description = ""
telemetry = false
requirements = []
cache_dir = "/home/runner/workspace/tipJarDapp/./.requirements"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.creator-vault]
path = "contracts/creator-vault.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
